### ISSUE TITLE
Exception thrown during R# 10.0.2 update

### ISSUE THREAD

**Issue by justinyoo** [StyleCop/StyleCop#33] opened 2015-12-25 10:19 UTC
Hi,

When I update R# 10.0.1 to 10.0.2, this extension throws an error like the screenshot below.

![image](https://cloud.githubusercontent.com/assets/1538528/12002214/cc7e6e3a-ab4c-11e5-9d4c-7ebbd7446e5d.png)

Of course there was no issue on 10.0.1. Not sure whether anyone has been aware this of.

Cheers,

**Comment by citizenmatt** [comment] 2016-01-06 10:46
This is a duplicate of #32. The errors can be safely ignored.

The installer is trying to load the extension at install time to look for potential custom build steps. The extension doesn't have any, so it's still correctly installed. However, due to the way the extension is built and laid out on disk, the installer can't load all of the dependencies, and reports an error, even though the extension is still installed.

There is actually a small bug in the installer, in that it doesn't report the error under certain circumstances - one of which is initial install. So the error was there in 10.0.1, but it wasn't reported.

**Closed by citizenmatt** 2016-01-06 10:46 UTC
