### ISSUE TITLE
UsingAliasDirectivesMustBeOrderedAlphabeticallyByAliasName - Orderer by Current Culture

### ISSUE THREAD

**Issue by hopp** [StyleCop/StyleCop#213] opened 2019-03-05 12:40 UTC
Why UsingAliasDirectivesMustBeOrderedAlphabeticallyByAliasName rule doesn't follow Invariant Culture ?

In Slovak Culture we have special letter 'CH', which goes after H. (a b c d e f g h ch i j ...)

For example:
Namespaces `Core.Build`, `Core.Chain` and `Core.Dependency` are ordered in English as
```
Core.Build
Core.Chain
Core.Dependency
```
but in Slovak
```
Core.Build
Core.Dependency
Core.Chain
```
as our code is English, but Windows locales is Slovak we have inconsistency.

**Comment by SanjayGuntur** [comment] 2019-03-06 11:35
Duplicate of #87.

**Closed by SanjayGuntur** 2019-03-06 11:35 UTC
